#!/bin/bash
# commande addUser qui permet de créer des utilisateurs

# Vérifie qu'il y a exactement un argument
if [ $# -ne 1 ]; then
    # \033[33m avec le -e permet de mettre le texte en jaune
    # et \033[0m permet de remettre la couleur blanche (sinon toutes les prochaines lignes seront en jaune)
    echo -e "\033[33m====== Usage: $0 <fichier_config> ======\033[0m"
    exit 1
fi

# Vérifie que l'argument est bien un fichier valide
if [ ! -f "$1" ]; then
    # \033[31m avec le -e permet de mettre le texte en rouge
    # et \033[0m permet de remettre la couleur blanche (sinon toutes les prochaines lignes seront en rouge)
    echo -e "\033[31m====== Erreur : $1 n'est pas un fichier valide ======\033[0m"
    exit 2
fi

# Vérifie que l'utilisateur a bien lancé le script en mode administrateur (avec un sudo avant)
# Lorsque qu'on fait un sudo id -u, ça renvoie 0 car on a l'UID 0
# Evite le $(whoami) = "root" car si un utilisateur s'appelle root, le script va fonctionner
if [ $(id -u) -ne 0 ]; then
    echo -e "\033[31m====== Erreur : Le script doit être exécuté en mode administrateur (sudo) ======\033[0m"
    exit 3
fi

# Stocke le nombre de lignes du fichier configuration
nbLines=$(wc -l < "$1") # Le < permet de retourner uniquement le nombre de lignes

mkdir -p /var/log
touch /var/log/install.log
log="/var/log/install.log"

# Analyse de chaque ligne du fichier
for ((i = 1; i <= $nbLines+1; i++)); do
    # Stocke la ligne numéro i dans une variable
    Lines=$(sed -n "${i}p" "$1" | tr -d " ")
    # Le <<< permet d'envoyer une chaîne de caractères sans utiliser un echo avec un pipe
    user=$(cut -d ',' -f1 <<< "$Lines")
    group=$(cut -d ',' -f2 <<< "$Lines")
    rephome=$(cut -d ',' -f3 <<< "$Lines")
    repskel=$(cut -d ',' -f4 <<< "$Lines")
    if [ $(awk -F',' '{print NF}' <<< $Lines) = 4 ] && [ -d "$repskel" ]&& [ -d "$rephome" ]; then
        # le -f permet de ne rien faire si le groupe existe déjà
        groupadd -f "$group"
        echo "Le groupe $group a été créé" >> $log
        # le > /dev/null 2>&1 sert à rediriger le message d'erreur "le répertoire personnel /home existe déjà." (il se produit car l'utilisateur aura défini /home comme home pour l'utilisateur)
        useradd -m -k "$repskel" -d "$rephome/$user" -g "$group" "$user" >> $log 2>&1
        if [ $? = 0 ]; then
            # \033[32m avec le -e permet de mettre le texte en vert
            # et \033[0m permet de remettre la couleur blanche (sinon toutes les prochaines lignes seront en vert)
            echo -e "\033[32m====== L'utilisateur $user a bien été créé dans le groupe $group ======\033[0m"
            echo "====== L'utilisateur $user a bien été créé dans le groupe $group ======" >> $log
            # mkdir -p pour créer les fichiers Downloads et Documents s'ils ne sont pas encore créés
            mkdir -p "$rephome/$user/Downloads" "$rephome/$user/Documents"
            if [ ! -f "$rephome/$user/.bashrc" ]; then
                touch "$rephome/$user/.bashrc"
                echo "Le fichier .bashrc a été créé" >> $log
            fi

            echo -e "alias e='emacs'\nalias w='wireshark'" >> $rephome/$user/.bashrc
            echo "Les alias e pour 'emacs' et w pour 'wireshark' ont été ajoutés pour l'utilisateur $user" >> $log
            # Ajouter le path /Scripts à la suite des paths déjà présents dans le fichier .bashrc
            echo -e 'export PATH="$PATH:/SAE/Scripts"' >> $rephome/$user/.bashrc
            echo "Le path '/SAE/Scripts' a bien été ajouté au .bashrc de l'utilisateur $user" >> $log
            # Rendre les dossiers à l'utilisateur (sinon ils sont à root)
            chown -R "$user:$group" "$rephome/$user"
            echo "Les droits du dossier $rephome/$user ont bien été donnés à $user du groupe $group" >> $log
        else
            echo -e "\033[31m====== Erreur : L'utilisateur $user n'a pas pu être ajouté (il existe peut-être déjà) ======\033[0m"
            echo "====== Erreur : L'utilisateur $user n'a pas pu être ajouté (il existe peut-être déjà) ======" >> $log
        fi
    else
        echo -e "\033[31m====== Erreur : La ligne $i est défaillante ======\033[0m"
        echo "====== Erreur : La ligne $i est défaillante ======" >> $log
    fi
    echo "================================================" >> $log
done
